# Generated by Django 3.1.4 on 2021-02-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_alt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
